### ISSUE TITLE
issue with Ramda when evaluating a SFCC object

### ISSUE THREAD

**Issue by darrell-roberts** [taurgis/salesforce-commerce-cloud-libraries#55]
Hi,

Thanks for porting these libraries. I tried to use Ramda hasPath.

Ex:

```javascript
var hasPath = require('ramda/hasPath');
hasPath(['profile', 'custom', 'customProp'])(customer)
```

I got the following error:
```
[ERROR: ScriptingException:ReferenceError: Unknown property '@@functional/placeholder' for class 'class dw.customer.Customer'. (ramda/internal/_isPlaceholder.js#4)]
```

I think the issue is when you use a property accessor with bracket notation in Rhino on a wrapped java object it raises an exception instead of returning 'undefined'.

Original ramda/internal/_isPlaceholder.js
```javascript
return a != null &&
         typeof a === 'object' &&
         a['@@functional/placeholder'] === true;
```
Possible workaround for Rhino java object:

```javascript
  if (a != null && typeof a === 'object') {
    try {
      return a['@@functional/placeholder'] === true; // A DW java object will raise an exception
    } catch (e) {
      return false;
    }
  } else {
    return false;
  }
```

**Comment by taurgis** [comment]
Your example code indeed solves the issue. I experienced a simular issue with Lodash. I have updated the code on develop with this.

Thank you!
